### ISSUE TITLE
Metatrader Exchange API

### ISSUE THREAD

**Issue by not-matthias** [barter-rs/barter-data-rs#20]
It'd be neat to be able to use Metatrader, because they are broker independant. They already have a ton of implementations for other exchanges, which would make this very useful.  

[Backtrader](https://www.backtrader.com/recipes/storesbrokersdata/mql5/mql5/) already implemented this [here](https://github.com/khramkov/Backtrader-MQL5-API) by using the [MQL5-JSON-API](https://github.com/khramkov/MQL5-JSON-API).

**Comment by just-a-stream** [comment]
That sounds interesting. 

I'm not familiar with MetaTrader. They provide WebSocket feeds?

**Comment by just-a-stream** [comment]
Also, is it a paid service?

**Comment by not-matthias** [comment]
> I'm not familiar with MetaTrader. They provide WebSocket feeds?
[MQL5-JSON-API](https://github.com/khramkov/MQL5-JSON-API) uses ZeroMQ, but Metatrader also supports Websockets. 

> Also, is it a paid service?
It's not (you can download it from here if you want to try it out: https://www.metatrader5.com/). You can just login with your broker account in the client. It's not open source though.

**Comment by just-a-stream** [comment]
Closing this now we've migrated this repo to the new barter-rs monorepo:
https://github.com/barter-rs/barter-rs
