### ISSUE TITLE
Confusing variable name and inappropriate value in subscription::OrderBook::mid_price

### ISSUE THREAD

**Issue by HereticSK** [barter-rs/barter-data-rs#24]
Hi, dear maintainers. Thanks for the great project!  I think I have found some problem in the implementation of `mid_price` and `volume_weighed_mid_price`, but I am new to rust, please correct me if I am wrong.

```Rust  
  pub fn mid_price(&self) -> f64 {
        match (self.bids.levels.first(), self.asks.levels.first()) {
            (Some(best_bid), Some(best_ask)) => mid_price(best_bid.price, best_ask.price),
            (Some(best_bid), None) => best_bid.price,
            (None, Some(best_bid)) => best_bid.price,
            (None, None) => 0.0,
        }
```
Firstly, IIUC, the third arm in the match block, `(None, Some(best_bid))`, is intended to match the case where only best ask is available and no bids. The matched value should be named `best_ask` instead of `best_bid`. The whole arm should be `(None, Some(best_ask)) => best_ask.price,`

Secondly, for the `(None, None)` case. It may not be a good idea to use 0.0 as a default value. price = 0.0 has its meaning in  trading: the instrument is for free. In practical use cases, the mid price of order book is typically used to indicate the "fair price" for the associated instrument. There are no quoting does not necessarily mean the instrument has zero price. Moreover, it is dangerous to set  an instrument's price as 0.0, especially when some selling signal is generated based on this price, which results in extremely low price as the order price, and may lead to trading loss.

From my experience, I would rather use `nan` as mid price in the empty order book case. But I don't know whether rust supports `nan`. Another option is to use `None`, but that requires changing the return type to `Option<f64>`

**Comment by just-a-stream** [comment]
Thanks for that @HereticSK !

Yes the naming of that "best_bid" for the best_ask is a mistake! 

You are correct regarding the selling us case. I'll take a look.

**Comment by just-a-stream** [comment]
@HereticSK I've just released a fix for this in barter-data-rs 0.6.6. 

Thanks again for raising a clear issue!

**Comment by just-a-stream** [comment]
Oh and if you are not on the discord you should join!

**Comment by just-a-stream** [comment]
https://discord.gg/3FRDUz84
