### ISSUE TITLE
Implementing new exchanges as independent crates

### ISSUE THREAD

**Issue by HereticSK** [barter-rs/barter-data-rs#36]
Under the current structure, implementing a new exchange requires merging new codes into the codebase, such as creating a new crate in the `exchange`, adding a new variant to the `ExchangeId` enum. 

But there are cases where users may want to implement some exotic exchanges that are not interested to other users. I hope we can have a better way to factor out exchange specific codes, so users can implement whatever exotic exchanges as they like, without affecting the whole project.

**Comment by just-a-stream** [comment]
Closing this now we've migrated this repo to the new barter-rs monorepo:
https://github.com/barter-rs/barter-rs
