### ISSUE TITLE
local `exchange_time` is used for orderbook subscription

### ISSUE THREAD

**Issue by jordy25519** [barter-rs/barter-data-rs#37]
hi, thanks for the crate!

it seems like the `exchange_time` field of `MarketEvent` is not set to the exchange given timestamp when using Binance L2 orderbook subscriptions.

https://github.com/barter-rs/barter-data-rs/blob/a6abe29e9c6195b40ba6c7c31f9586d9a534c112/src/subscription/book.rs#L278-L280

`book.last_update_time` is set here to `Utc::now()`
https://github.com/barter-rs/barter-data-rs/blob/a6abe29e9c6195b40ba6c7c31f9586d9a534c112/src/transformer/book.rs#L141-L144

I'm interested in the exchange given timestamp to check latency between my service and the exchange feed

**Comment by just-a-stream** [comment]
Closing this now we've migrated this repo to the new barter-rs monorepo:
https://github.com/barter-rs/barter-rs
