### ISSUE TITLE
Add time frame/series element to Candle struct

### ISSUE THREAD

**Issue by SeanEClarke** [barter-rs/barter-data-rs#40]
As part of Barter feature request (https://github.com/barter-rs/barter-rs/issues/21) to implement strategies utilising multiple timeframes, a precursor to a possible implementation of this is to add a time frame element to the Candle struct so you can determine to what period the OHLCV apply to.

**Comment by SeanEClarke** [comment]
Raised https://github.com/barter-rs/barter-data-rs/pull/41

**Comment by just-a-stream** [comment]
Closing this now we've migrated this repo to the new barter-rs monorepo:
https://github.com/barter-rs/barter-rs
