### ISSUE TITLE
Add GitHub Action for code testing

### ISSUE THREAD

**Issue by Crauzer** [barter-rs/barter-data-rs#5]
This will allow for verification of incoming pull requests and promote testing code

Relevant actions:
https://github.com/marketplace/actions/rust-cargo
https://github.com/marketplace/actions/rust-toolchain

**Comment by carpetmaker** [comment]
I can add this right after merging https://github.com/barter-rs/barter-rs/issues/5 on Friday

**Comment by just-a-stream** [comment]
Closing this now we've migrated this repo to the new barter-rs monorepo:
https://github.com/barter-rs/barter-rs
