### ISSUE TITLE
Can China Futures CTP interface be supported

### ISSUE THREAD

**Issue by kingmo888** [barter-rs/barter-data-rs#9]
Similar implementations include vnpy, which supports many exchanges, as well as China's futures market and stock market. Unfortunately, the efficiency of the Python based framework is not very satisfactory.
I have been looking for a Rust based framework. I was lucky to find Barter, but only support crypto exchanges.

Development Documentation：CTP Client Development Guide.pdf
[CTP_Client_Development_Guide.pdf](https://gitlab.com/open-source-keir/financial-modelling/trading/barter-data-rs/uploads/e2379d3c75d577cf1e4bb32e623afb99/CTP_Client_Development_Guide.pdf)

c++ code & dll is:[v6.6.8_traderapi.zip](https://gitlab.com/open-source-keir/financial-modelling/trading/barter-data-rs/uploads/36bb420188062f950bac71e22d6aef23/v6.6.8_traderapi.zip)
(I found the trust encapsulation of the ctp interface, but I don't know how to combine it with barter:https://github.com/WiSaGaN/ctp-rs)

test account is :https://www.simnow.com.cn/   (MarketPrice not need account)

**Comment by carpetmaker** [comment]
Hello @kingmo888 !

Thanks for your question / suggestion!
This project is still very small and is gaining traction...
Currently most of the contributors are focused on enhancing the crypto exchanges support,
even though the design goal of the project is indeed to be agnostic of different types of assets traded.
So, my advice is that you wait a little bit until we organise the project & update docs regarding contributing, project architecture, small guides for adding new data sources etc. and then wait for either an adopter of this issue, or start working on it on your own.

If you have any addition questions, it is best that you hop on our discord server (https://discord.gg/wE7RqhnQMV),
and chat there with the rest of community.

Sincerely,
@carpetmaker

**Comment by carpetmaker** [comment]
>By the way, taking [VNPY](https://github.com/vnpy/vnpy) as an example,

This project looks amazing! It seems to have a very advanced feature set, is well-documented and seems to be very popular / very actively worked on. There is however an unfortunate language barrier (most of the resources are in Chinese), but that is where I will definitely use your occasional help of translating the resources used for the potential reference implementation later on.

Feel free to join the [discord server](https://discord.gg/wE7RqhnQMV) here, so you can chat with the rest of the community.
(hopefully you don't have any geo-location / regional restrictions)

**Comment by just-a-stream** [comment]
Closing this now we've migrated this repo to the new barter-rs monorepo:
https://github.com/barter-rs/barter-rs
